import pyemu
import pandas as pd
import os
import shutil
from pathlib import Path

# configure paths
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PEST_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, "..", "pest"))
MODEL_WS = os.path.abspath(os.path.join(SCRIPT_DIR, "..", "sims", "real-basis", "real"))
RESULTS_DIR = Path(r"c:\Python\Personal\kfm-ms\codes\results")
PYTHON_LOC = Path(r"c:\Python\Personal\kfm-ms\.venv\Scripts\python.exe")
MASTER_TRUTH_FILE = "master_truth.csv"  # filename stored in pest_dir


def build_modular_pst(level):
    print(f"\ninitializing pest setup in: {PEST_DIR}")

    # initialise the pest-from workflow using the reference model workspace
    pf = pyemu.utils.PstFrom(
        original_d=MODEL_WS,
        new_d=PEST_DIR,
        remove_existing=True,
        longnames=True
    )

    # copy the surrogate response matrix into the pest workspace
    # this file is not part of the modflow model, but is required by the inversion workflow
    source_g = os.path.join(RESULTS_DIR, "G_real_basis.npy") 
    dest_g = os.path.join(PEST_DIR, "G_real_basis.npy")
    shutil.copy(source_g, dest_g)

    # register pumping rates as adjustable parameters
    pf.add_parameters(
        filenames="master_truth.csv",
        par_type="grid", 
        index_cols=["r", "c", "sp"],
        use_cols=["q"]
    )

    # copy and register the observation file so pest can read the observation structure
    source_obs = os.path.join(MODEL_WS, "obs.csv") 
    dest_dummy = os.path.join(PEST_DIR, "dummy_obs.csv")
    shutil.copy(source_obs, dest_dummy)

    # add observations using the copied file structure
    pf.add_observations("obs.csv", index_cols=["obsnme"], use_cols=["obsval"])

    # add the surrogate model function to the autogenerated forward run script
    pf.add_py_function("surrogate.py", call_str="run_surrogate()", is_pre_cmd=False)
    
    # build the pst control file
    pst = pf.build_pst()

    # define the command used by pestpp to execute the forward model
    pst.model_command = f'"{PYTHON_LOC}" forward_run.py'

    pst.control_data.noptmax = 10
    pst.pestpp_options = {} 

    # set default parameter behaviour before applying level-specific access rules
    pst.parameter_data.loc[:, "partrans"] = "fixed"
    pst.parameter_data.loc[:, "parval1"] = 1e-6
    pst.parameter_data.loc[:, "parlbnd"] = 1e-6
    pst.parameter_data.loc[:, "parubnd"] = 500.0

    # load the master truth file for parameter subsetting
    df_truth = pd.read_csv(os.path.join(PEST_DIR, MASTER_TRUTH_FILE))

    if level == "1":
        print(">>> mode: level 1 (full knowledge)")
        for _, row in df_truth.iterrows():
            # match the parameter naming convention used by pstfrom
            tag = f"r:{int(row.r)}_c:{int(row.c)}_sp:{int(row.sp)}"
            well_mask = pst.parameter_data.index.str.contains(tag)
            pst.parameter_data.loc[well_mask, "partrans"] = "log"
            pst.parameter_data.loc[well_mask, "parval1"] = 1.0

    elif level == "2":
        print(">>> mode: level 2 (known locations)")
        unique_locs = df_truth[["r", "c"]].drop_duplicates()
        for _, row in unique_locs.iterrows():
            loc_tag = f"r:{int(row.r)}_c:{int(row.c)}"
            mask = pst.parameter_data.index.str.contains(loc_tag)
            pst.parameter_data.loc[mask, "partrans"] = "log"
            pst.parameter_data.loc[mask, "parval1"] = 1.0

    elif level == "3":
        print(">>> mode: level 3 (blind)")
        pst.parameter_data.loc[:, "partrans"] = "log"
        pst.parameter_data.loc[:, "parval1"] = 1.0

    final_pst_path = os.path.join(PEST_DIR, f"inversion_level_{level}.pst")
    pst.write(final_pst_path, version=2)
    
    # append pestpp options required for the inversion workflow
    options_block = [
        "\n",
        "* pestpp options\n",
        "run_manage multiprocess\n",
        "max_run_fail 5\n",
        "n_iter_base -1\n",
        "n_iter_super 3\n",
        "lambda_scale_fac 1.0\n"
    ]

    with open(final_pst_path, "a") as f:
        f.writelines(options_block)

    print(f"\n[!] Success: Control file created: inversion_level_{level}.pst")
    print("[!] Note: pestpp options block appended to the control file.")


if __name__ == "__main__":
    choice = input("\nselect level (1, 2, or 3): ").strip()
    if choice in ["1", "2", "3"]:
        build_modular_pst(choice)